# 在 下面 写 需要 的 消息 信息

builtin_interfaces/Time stamp       # 记录 时间辍

# string 为 ros2 中 内置的 字符串类型
string host_name                    # 系统 主机 的 名字

# float32 为 ros2 中 内置的 字符串类型
float32 cpu_percent                 # CPU 使用率

float32 memory_percent              # 内存 使用率

float32 memory_total                # 内存 总大小

float32 memory_available            # 剩余 内存大小

float64 net_sent                    # 网络 数据 发送 总量  1 MB = 8MB

float64 net_recv                    # 网络 数据 接收 总量

